<a href="https://colab.research.google.com/github/mail2chandanadasari-code/mail2chandanadasari-CSPT/blob/main/day-3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

In [32]:
df = pd.read_excel('/content/CineMetrics_Dataset.xlsx')

In [9]:
df.head()

,Movie_ID,Title,Genre,Release_Year,Duration_Min,Language,Country,Streaming_Platform,Budget_Million_USD,Revenue_Million_USD,IMDB_Rating,Votes_Thousands,Critic_Score,Director_Experience_Years
0,1,The Crimson Odyssey,Animation,2013,NaN,French,France,HBO Max,33.8,43.9,3.6,315.9,46.0,7.0
1,2,The Sacred Echo,Documentary,2014,88.0,Hindi,India,Prime Video,58.4,183.8,6.6,79.9,NaN,13.0
2,3,The Rising Illusion,Action,1995,105.0,Spanish,Mexico,HBO Max,12.8,13.8,6.8,71.9,32.0,30.0
3,4,The Crimson Awakening,Sci-Fi,2003,107.0,German,Germany,Netflix,11.4,27.8,8.0,74.6,81.0,33.0
4,5,The Last Legacy,Sci-Fi,2020,82.0,Hindi,India,Netflix,37.1,13.1,NaN,26.1,47.0,15.0

In [10]:
df.shape

(300, 14)

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 300 entries, 0 to 299
Data columns (total 14 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Movie_ID                   300 non-null    int64
 1   Title                      300 non-null    object
 2   Genre                      288 non-null    object
 3   Release_Year               300 non-null    int64
 4   Duration_Min               285 non-null    float64
 5   Language                   291 non-null    object
 6   Country                    300 non-null    object
 7   Streaming_Platform         291 non-null    object
 8   Budget_Million_USD         264 non-null    float64
 9   Revenue_Million_USD        273 non-null    float64
 10  IMDB_Rating                282 non-null    float64
 11  Votes_Thousands            285 non-null    float64
 12  Critic_Score               279 non-null    float64
 13  Director_Experience_Years  288 non-null    float64
dtypes: float64(7), int64(2), object(5)
memory usage: 32.9+ KB

In [33]:
df["Duration_Min"] = df["Duration_Min"].fillna(df["Duration_Min"].mean())
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 300 entries, 0 to 299
Data columns (total 14 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Movie_ID                   300 non-null    int64
 1   Title                      300 non-null    object
 2   Genre                      288 non-null    object
 3   Release_Year               300 non-null    int64
 4   Duration_Min               300 non-null    float64
 5   Language                   291 non-null    object
 6   Country                    300 non-null    object
 7   Streaming_Platform         291 non-null    object
 8   Budget_Million_USD         264 non-null    float64
 9   Revenue_Million_USD        273 non-null    float64
 10  IMDB_Rating                282 non-null    float64
 11  Votes_Thousands            285 non-null    float64
 12  Critic_Score               279 non-null    float64
 13  Director_Experience_Years  288 non-null    float64
dtypes: float64(7), int64(2), object(5)
memory usage: 32.9+ KB

In [34]:
df["Budget_Million_USD"] = df["Budget_Million_USD"].fillna(df["Budget_Million_USD"].mean())
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 300 entries, 0 to 299
Data columns (total 14 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Movie_ID                   300 non-null    int64
 1   Title                      300 non-null    object
 2   Genre                      288 non-null    object
 3   Release_Year               300 non-null    int64
 4   Duration_Min               300 non-null    float64
 5   Language                   291 non-null    object
 6   Country                    300 non-null    object
 7   Streaming_Platform         291 non-null    object
 8   Budget_Million_USD         300 non-null    float64
 9   Revenue_Million_USD        273 non-null    float64
 10  IMDB_Rating                282 non-null    float64
 11  Votes_Thousands            285 non-null    float64
 12  Critic_Score               279 non-null    float64
 13  Director_Experience_Years  288 non-null    float64
dtypes: float64(7), int64(2), object(5)
memory usage: 32.9+ KB

In [36]:
df["Revenue_Million_USD"] = df["Revenue_Million_USD"].fillna(df["Revenue_Million_USD"].mean())
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 300 entries, 0 to 299
Data columns (total 14 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Movie_ID                   300 non-null    int64
 1   Title                      300 non-null    object
 2   Genre                      288 non-null    object
 3   Release_Year               300 non-null    int64
 4   Duration_Min               300 non-null    float64
 5   Language                   291 non-null    object
 6   Country                    300 non-null    object
 7   Streaming_Platform         291 non-null    object
 8   Budget_Million_USD         300 non-null    float64
 9   Revenue_Million_USD        300 non-null    float64
 10  IMDB_Rating                282 non-null    float64
 11  Votes_Thousands            285 non-null    float64
 12  Critic_Score               279 non-null    float64
 13  Director_Experience_Years  288 non-null    float64
dtypes: float64(7), int64(2), object(5)
memory usage: 32.9+ KB

In [38]:
df["IMDB_Rating"] = df["IMDB_Rating"].fillna(df["IMDB_Rating"].mean())
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 300 entries, 0 to 299
Data columns (total 14 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Movie_ID                   300 non-null    int64
 1   Title                      300 non-null    object
 2   Genre                      288 non-null    object
 3   Release_Year               300 non-null    int64
 4   Duration_Min               300 non-null    float64
 5   Language                   291 non-null    object
 6   Country                    300 non-null    object
 7   Streaming_Platform         291 non-null    object
 8   Budget_Million_USD         300 non-null    float64
 9   Revenue_Million_USD        300 non-null    float64
 10  IMDB_Rating                300 non-null    float64
 11  Votes_Thousands            285 non-null    float64
 12  Critic_Score               279 non-null    float64
 13  Director_Experience_Years  288 non-null    float64
dtypes: float64(7), int64(2), object(5)
memory usage: 32.9+ KB

In [40]:
df["Votes_Thousands"] = df["Votes_Thousands"].fillna(df["Votes_Thousands"].mean())
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 300 entries, 0 to 299
Data columns (total 14 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Movie_ID                   300 non-null    int64
 1   Title                      300 non-null    object
 2   Genre                      288 non-null    object
 3   Release_Year               300 non-null    int64
 4   Duration_Min               300 non-null    float64
 5   Language                   291 non-null    object
 6   Country                    300 non-null    object
 7   Streaming_Platform         291 non-null    object
 8   Budget_Million_USD         300 non-null    float64
 9   Revenue_Million_USD        300 non-null    float64
 10  IMDB_Rating                300 non-null    float64
 11  Votes_Thousands            300 non-null    float64
 12  Critic_Score               279 non-null    float64
 13  Director_Experience_Years  288 non-null    float64
dtypes: float64(7), int64(2), object(5)
memory usage: 32.9+ KB

In [42]:
df["Critic_Score"] = df["Critic_Score"].fillna(df["Critic_Score"].mean())
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 300 entries, 0 to 299
Data columns (total 15 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Movie_ID                   300 non-null    int64
 1   Title                      300 non-null    object
 2   Genre                      288 non-null    object
 3   Release_Year               300 non-null    int64
 4   Duration_Min               300 non-null    float64
 5   Language                   291 non-null    object
 6   Country                    300 non-null    object
 7   Streaming_Platform         291 non-null    object
 8   Budget_Million_USD         300 non-null    float64
 9   Revenue_Million_USD        300 non-null    float64
 10  IMDB_Rating                300 non-null    float64
 11  Votes_Thousands            300 non-null    float64
 12  Critic_Score               300 non-null    float64
 13  Director_Experience_Years  288 non-null    float64
 14  Critic_Score               300 non-null    float64
dtypes: float64(8), int64(2), object(5)
memory usage: 35.3+ KB

In [43]:
df["Director_Experience_Years"] = df["Director_Experience_Years"].fillna(df["Director_Experience_Years"].mean())
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 300 entries, 0 to 299
Data columns (total 15 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Movie_ID                   300 non-null    int64
 1   Title                      300 non-null    object
 2   Genre                      288 non-null    object
 3   Release_Year               300 non-null    int64
 4   Duration_Min               300 non-null    float64
 5   Language                   291 non-null    object
 6   Country                    300 non-null    object
 7   Streaming_Platform         291 non-null    object
 8   Budget_Million_USD         300 non-null    float64
 9   Revenue_Million_USD        300 non-null    float64
 10  IMDB_Rating                300 non-null    float64
 11  Votes_Thousands            300 non-null    float64
 12  Critic_Score               300 non-null    float64
 13  Director_Experience_Years  300 non-null    float64
 14  Critic_Score               300 non-null    float64
dtypes: float64(8), int64(2), object(5)
memory usage: 35.3+ KB

In [44]:
df.describe()

,Movie_ID,Release_Year,Duration_Min,Budget_Million_USD,Revenue_Million_USD,IMDB_Rating,Votes_Thousands,Critic_Score,Director_Experience_Years,Critic_Score
count,300.000000,300.000000,300.000000,300.000000,300.000000,300.000000,300.000000,300.000000,300.000000,300.000000
mean,150.500000,2008.680000,112.564912,32.051515,83.763736,6.465957,89.589123,59.390681,19.805556,59.390681
std,86.746758,8.854695,20.601007,32.329384,102.079249,1.298485,76.991943,14.853174,11.491907,14.853174
min,1.000000,1995.000000,70.000000,2.100000,0.000000,3.200000,5.000000,25.000000,0.000000,25.000000
25%,75.750000,2001.000000,99.000000,13.975000,24.300000,5.600000,29.600000,48.750000,11.000000,48.750000
50%,150.500000,2009.000000,112.564912,25.400000,60.000000,6.465957,72.300000,59.390681,19.805556,59.390681
75%,225.250000,2016.250000,126.250000,34.175000,103.750000,7.400000,125.900000,69.000000,29.000000,69.000000
max,300.000000,2024.000000,166.000000,300.000000,906.000000,9.700000,413.800000,100.000000,40.000000,100.000000

In [45]:
df.isnull().sum()

Movie_ID                      0
Title                         0
Genre                        12
Release_Year                  0
Duration_Min                  0
Language                      9
Country                       0
Streaming_Platform            9
Budget_Million_USD            0
Revenue_Million_USD           0
IMDB_Rating                   0
Votes_Thousands               0
Critic_Score                  0
Director_Experience_Years     0
Critic_Score                  0
dtype: int64

In [47]:
numeric_cols = ['Duration_Min', 'Budget_Million_USD', 'Revenue_Million_USD',
                'IMDB_Rating', 'Votes_Thousands', 'Critic_Score',
                'Director_Experience_Years']

In [48]:
for col in numeric_cols:
    df[col] = df[col].fillna(df[col].mean())

In [49]:
df[numeric_cols].isnull().sum()

Duration_Min                 0
Budget_Million_USD           0
Revenue_Million_USD          0
IMDB_Rating                  0
Votes_Thousands              0
Critic_Score                 0
Director_Experience_Years    0
dtype: int64

In [50]:
df.isnull().sum()

Movie_ID                      0
Title                         0
Genre                        12
Release_Year                  0
Duration_Min                  0
Language                      9
Country                       0
Streaming_Platform            9
Budget_Million_USD            0
Revenue_Million_USD           0
IMDB_Rating                   0
Votes_Thousands               0
Critic_Score                  0
Director_Experience_Years     0
Critic_Score                  0
dtype: int64

In [51]:
before_rows = df.shape[0]
before_rows

300

In [52]:
df = df.dropna()

In [53]:
after_rows = df.shape[0]
print('Rows before:', before_rows)
print('Rows after: ', after_rows)
print('Dropped:    ', before_rows - after_rows)

Rows before: 300
Rows after:  271
Dropped:     29

In [54]:
df.isnull().sum().sum()

np.int64(0)

In [55]:
from sklearn.preprocessing import MinMaxScaler